dist: trusty
sudo: required

language: generic
#node_js:
 # - "stable"
addons:
  sonarcloud:
    organization: "tanujamedisetti87-github"
    token:
      secure: "c31adcd738465686855224f7f9b30c8ec5008271"
  #sauce_connect:
   # username: "TanujaMedisetti87"
   # access_key: "130dda79-1dea-45cd-849c-24cfbe048884"
    
script:
  - sonar-scanner
  

before_deploy:
  - cd ..
  - zip -r mahesh1 *
  - mkdir -p "dpl_cd_upload"
  - mv mahesh1.zip dpl_cd_upload/mahesh1.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: tanuja123
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo:  TanujaMedisetti87/test4
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: tanuja123
    key: mahesh1.zip
    bundle_type: zip
    application: TestApplication
    deployment_group: TestApplication
    region: us-east-1
    on:
      repo: TanujaMedisetti87/test4
      all_branches: true
after_deploy:
  - echo "Performing after deploy procedures..."
  - unzip mahesh1.zip
