version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    
hooks:

  BeforeInstall:
    - location: scripts/npm-before.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60
    
    
